TRUNCATE TABLE CATEGORIE;
TRUNCATE TABLE COMPTE;
TRUNCATE TABLE PRODUIT;
TRUNCATE TABLE UTILISATEUR;
TRUNCATE TABLE OFFRE;
TRUNCATE TABLE CARACPRODUIT;
TRUNCATE TABLE APOURMERE;
TRUNCATE TABLE OFFREGAGNANTE;